services:
  - type: web
    name: bug-triage-assistant
    env: python
    repo: https://github.com/Ankita0sharma/bug_triage_Assistant
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    plan: free
